/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jvitorsouzadesign (https://sketchfab.com/jvitorsouzadesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-salazar-downloadable-eeed09437afb4e1ea8a6ff3b0e9964ad
Title: Skull Salazar (Downloadable)
*/

import { useRef,useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import skullScene from '../assets/3d/skull.glb'

const Skull = (props) => {
    const skullRef = useRef()

    const { nodes, materials } = useGLTF(skullScene);
    return (
        <a.group ref={skullRef}{...props}>
            <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Rosa_material}
            />
            <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.defaultMat_material}
            />
        </a.group>
    )
}

export default Skull