/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jvitorsouzadesign (https://sketchfab.com/jvitorsouzadesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-salazar-downloadable-eeed09437afb4e1ea8a6ff3b0e9964ad
Title: Skull Salazar (Downloadable)
*/

import { useRef,useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'

import skullScene from '../assets/3d/skull.glb'

const Skull = ({ ...props }) => {
    const skull = useGLTF(skullScene)
    const skullRef = useRef()

    useFrame((_, delta) => {
        skullRef.current.rotation.y += 0.45 * delta
    })

    return (
        <mesh
        ref={skullRef} {...props}>
            <primitive object={skull.scene} />
        </mesh>
    )
}

export default Skull